//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Meta.WitAi.Composer.Handlers.ComposerActionEvent))]
	public class PropertyProvider_Meta_WitAi_Composer_Handlers_ComposerActionEvent : Unity.VisualScripting.SerializedPropertyProvider<Meta.WitAi.Composer.Handlers.ComposerActionEvent>
	{
	}
}
